New db function: execMany() - execute many statements with detailed results
sql-js/sql.js pull request #413
Opened 2020-08-22 07:15 UTC by cpainterwakefield

Consider this a feature request - I need functionality as implemented here for my particular use case.  So I wrote some code for it - please let me know if this is something you are willing to incorporate into sql-js.  Thanks!

2020-09-06 19:08 UTC, cpainterwakefield commented
Hi, just wondering if anyone has taken a look at this.  These are features I need for my use case; I'd like to get some sense of whether or not you might include in sql-js in some form, either in current version or next.  If in current version great, if in next version, I might fork and use my fork until the next version comes out.  Thanks!

2020-09-10 17:44 UTC, Taytay commented
I haven't taken a detailed look at the code yet, and am not particularly qualified to do so, but I have needed something similar, so I appreciate the contribution. I did notice that the statements don't allow for parameters, which would limit its use in my case and _might_ lead to folks doing some dangerous SQL string manipulation to get this to work in their case. Without knowing the code well, I don't know how hard it would be to make it support parameters, but that was the first thing to stood out to me.

2020-09-10 18:29 UTC, cpainterwakefield commented
It would be possible to include parameters, and obviously that would be preferable for use cases where SQL injection is a possibility.  The main thing there would be to work out the interface details (how best to provide the parameters to the function - as an array of arrays matching the # of queries, or maybe just an array of parameters to be used in order?)  Once that was decided, I don't think it would be terribly hard to expand the function to use the parameters.

2020-10-11 17:23 UTC, lovasoa requested changes
I made comments on the implementation details of the PR. But my overall feeling on this is that it tries to address a very specific use case, and that the same could be achieved on the user side if we offered a more generic API. We could have a simple Database.iter_statements API that takes a string and returns an iterable over `Statement` objects. This would be more general, and would allow users to replicate this functionality in an idiomatic manner. Users could also bind parameters to their statements as they see fit. And we could additionally create a `normalized_sql` method on `Statement` that wraps sqlite3_normalized_sql.

2020-10-11 17:23 UTC, lovasoa commented on src/api.js
> +                continue;
We can avoid this continue too

2020-10-15 09:36 UTC, lovasoa commented
Closed in favor of #429

2020-10-15 09:36 UTC, closed without merging